name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-scan-sign-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # For GHCR push
      security-events: write  # For SARIF upload to Code Scanning

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-push  # ID for digest
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Install Trivy manually
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.67.0/trivy_0.67.0_Linux-64bit.tar.gz
        tar -xzf trivy_0.67.0_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/
        trivy --version  # Verify install (should show 0.67.0, no warnings)

    - name: Scan image with Trivy
      id: trivy
      run: trivy image --exit-code 0 --no-progress --severity CRITICAL,HIGH --format sarif --output trivy-results.sarif --skip-version-check ghcr.io/${{ github.repository }}:latest  # Set
